module.exports = {
  apps: [
    {
      name: 'trend-service',
      script: 'npx',
      args: 'ts-node backend/trend-service/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'script-service',
      script: 'npx',
      args: 'ts-node backend/script-service/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'render-service',
      script: 'npx',
      args: 'ts-node backend/render-service/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'moderation-service',
      script: 'npx',
      args: 'ts-node backend/moderation-service/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'recommendation-service',
      script: 'npx',
      args: 'ts-node backend/recommendation-service/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'gateway-service',
      script: 'npx',
      args: 'ts-node backend/api-gateway/src/main.ts',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
  ],
};
