import { LlmScriptProvider } from '../interfaces/llm-script-provider.interface';

export class YohPalBrainLlmProvider implements LlmScriptProvider {
  async generateScript(prompt: string, _context?: Record<string, unknown>) {
    return {
      title: `AI: ${prompt.slice(0, 50)}`,
      hook: 'Here is something incredible...',
      body: 'Script generated by YohPal Brain LLM provider.',
      cta: 'Follow for daily content!',
      metadata: { provider: 'yohpal_brain', model: 'yohpal-llm-v1' },
    };
  }
}
