export type ScriptPromptInput = {
  topic: string;
  category: string;
  region?: string | null;
  country?: string | null;
  language: string;
  durationSeconds: number;
};

export function buildSeedVideoScriptPrompt(input: ScriptPromptInput): string {
  return `
Write a short, engaging video script for YohPal Live.

Topic: ${input.topic}
Category: ${input.category}
Region: ${input.region || 'Global'}
Language: ${input.language}
Duration: ${input.durationSeconds} seconds

Rules:
1. Start with a strong hook.
2. Use simple, friendly, energetic language.
3. Avoid hate, insults, explicit content, political manipulation, medical claims, legal claims, or financial promises.
4. Keep it suitable for early YohPal Live users.
5. Add a soft call-to-action at the end.
6. Do not mention that this content was generated by AI.

Return: Title, Hook, Body, CTA.
  `;
}

export function buildFactCheckPrompt(script: string): string {
  return `
Review the following YohPal Live seed video script for factual safety.

Script: ${script}

Return:
1. factScore from 0 to 1
2. unsafeClaims list
3. correctionNotes
4. requiresHumanReview true/false
  `;
}

export function buildViralPredictionPrompt(script: string): string {
  return `
Score this YohPal Live short-video script for potential performance.

Script: ${script}

Return:
1. viralProbability
2. engagementScore
3. watchTimeScore
4. shareScore
5. commentScore
6. qualityScore
  `;
}
